<center>

![](recursos/img/logoitqv1.jpg)

</center>

## PAO26-26-Python 1,NumPy

<center>

![](recursos/img/python_logo.png)

</center>

*Cynthia Cuñez*

# 1 NumPy ndarray

- NumPy (*Numerical Python*) es la de facto librería estándar para análisis numérico en Python.
- Estructura de datos multidimensional eficiente (escrita en C): `ndarray`.
- Colección de funciones para álgebra lineal, estadística descriptiva.
- Ayuda al procesamiento de datos (`np.where`).

In [2]:
#importar libreria
import numpy as np

### Performance Sample, NumPy vs Plain Python

In [3]:
my_list = list(range(10000000)) # Utilizando Listas Python
%time my_list = [x * 2 for x in my_list]

CPU times: total: 1.45 s
Wall time: 1.62 s


In [4]:
my_arr = np.arange(10000000) # Utilizando NumPy Arrays
%time my_arr2 = my_arr * 2

CPU times: total: 46.9 ms
Wall time: 36.1 ms


### Formas de crear ndarrays

In [5]:
array = np.array([ [2,71,0,34], [2,171,-35,34] ]) # 2D
print(array)

[[  2  71   0  34]
 [  2 171 -35  34]]


In [7]:
shopping_list = [ ['onions', 'carrots', 'celery'], ['apples', 'oranges','grapes'] ] # 2D
array = np.array(shopping_list) # convertir una lista en una ndarray
print(array)
print(type(array))

[['onions' 'carrots' 'celery']
 ['apples' 'oranges' 'grapes']]
<class 'numpy.ndarray'>


In [8]:
print(np.array([100,10,1])) # array a partir de una lista
print(np.arange(2,10,2.1)) # array a partir de una secuencia(range) 1D

[100  10   1]
[2.  4.1 6.2 8.3]


In [9]:
# Generar arrays con valores fijos
print(np.zeros(2)) # 1D
print(np.ones((4,3))) # matrix 2x2
print(np.empty((2,2,2))) # matrix 2x2x2, no inicializados
print(np.full((5,2),2)) # matrix 5x2
print(np.eye(3)) # matrix identity

[0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[[9.88e-324 3.51e-322]
  [0.00e+000 1.68e-322]]

 [[9.88e-324 8.45e-322]
  [      nan 1.68e-322]]]
[[2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Obtener información sobre ndarray

In [10]:
my_ndarray = np.array([2,71,0,34])
print(my_ndarray)

[ 2 71  0 34]


In [11]:
print(my_ndarray.argmax()) # índice del valor más alto
print(np.amax(my_ndarray))
print(my_ndarray.argmin()) # índice del valor más bajo
print(np.amin(my_ndarray))
print(my_ndarray.nonzero()) # retorna los índices de los elementos distintos 0

1
71
2
0
(array([0, 1, 3]),)


In [12]:
my_ndarray = np.full((5, 4,2), 2) # matrix 5x2x2
print(my_ndarray)
print(my_ndarray.size) # número de elementos
print(my_ndarray.shape) # dimensiones
print(my_ndarray.ndim) # número de dimensiones

[[[2 2]
  [2 2]
  [2 2]
  [2 2]]

 [[2 2]
  [2 2]
  [2 2]
  [2 2]]

 [[2 2]
  [2 2]
  [2 2]
  [2 2]]

 [[2 2]
  [2 2]
  [2 2]
  [2 2]]

 [[2 2]
  [2 2]
  [2 2]
  [2 2]]]
40
(5, 4, 2)
3


In [13]:
my_ndarray = np.array([2,71,0,34])
print(my_ndarray.size) # número de elementos
print(my_ndarray.shape) # dimensiones
print(my_ndarray.ndim) # número de dimensiones


4
(4,)
1


* Redimensionar los datos